// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBook(ctx context.Context, id int32) error
	DeleteLoan(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetBook(ctx context.Context, id int32) (Book, error)
	GetBookByISBN(ctx context.Context, isbn string) (Book, error)
	GetLoan(ctx context.Context, id int32) (Loan, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListActiveLoans(ctx context.Context, arg ListActiveLoansParams) ([]Loan, error)
	ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error)
	ListLoansByUser(ctx context.Context, arg ListLoansByUserParams) ([]Loan, error)
	ListOverdueLoans(ctx context.Context, arg ListOverdueLoansParams) ([]Loan, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ReturnBook(ctx context.Context, id int32) (Loan, error)
	SearchBooks(ctx context.Context, arg SearchBooksParams) ([]Book, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
